repos:
  - repo: local
    hooks:
      - id: trufflehog
        name: TruffleHog
        description: Detect secrets in commits
        entry: bash -c 'files=$(git diff --cached --name-only --diff-filter=ACMRT); [ -z "$files" ] || trufflehog filesystem $files --no-verification --fail'
        language: system
        stages: ["pre-commit"]