repos:
  - repo: local
    hooks:
      - id: trufflehog
        name: TruffleHog
        description: Detect secrets in commits
        entry: bash -c 'trufflehog git file://. --since-commit HEAD --no-verification --fail'
        language: system
        stages: ["commit", "push"]